// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { Monsters, MonstersData, MonstersTableId } from "./tables/Monsters.sol";
import { CaughtMonsters, CaughtMonstersData, CaughtMonstersTableId } from "./tables/CaughtMonsters.sol";
