// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum MonsterTypes {
  Unknown,
  Normal,
  Grass,
  Fire,
  Water
}

enum Direction {
  Unknown,
  Up,
  Down,
  Right,
  Left
}
